### ISSUE TITLE
Ability to see installer progress.

### ISSUE THREAD

**Issue by IntoTheVoid-900** [ltGuillaume/LibreWolf-WinUpdater#1]
Right now when I start an update it tells me I need an update but gives me no indication of what's happening or when it's done. Can you please add options to either

1. Show the installer
2. Show installer progress with notification or pinned tray icon

**Comment by ltGuillaume** [comment]
Heya! While the idea was to mimic an automatic updates service (so not having UI feedback was kind of the point), I guess I should add more feedback for when the user runs the updater manually (i.e. not via a scheduled task).

Here are the two options:

1. Show a dialog with the download progress
2. Show the installer and automatically click the Next / Install / Finish buttons, so the user doesn't have to.

or

1. Add progress via notifications: "Downloading LibreWolf v97.0..." / "Installing LibreWolf v97.0..."

Obviously the second is a lot easier to implement.

**Comment by ltGuillaume** [comment]
[LibreWolf-WinUpdater_1.2.3test.zip](https://github.com/ltGuillaume/LibreWolf-WinUpdater/files/8088821/LibreWolf-WinUpdater_1.2.3test.zip)

This version more verbose when started manually. Does this work for you?

**Comment by IntoTheVoid-900** [comment]
I am sorry, I didn't explain this well. I understand you want it to be like an automatic update service, there is no way to tell when the update is finished downloading and installing, and when LibreWolf is ready to reopen. The notification service would be great.

**Comment by ltGuillaume** [comment]
But there is. You always get a notification as soon as LibreWolf is updated. So I don't really know what you mean then.

**Comment by IntoTheVoid-900** [comment]
Wait, am I just being stupid? When I boot Librewolf after startup I often get the updater notification. When that appears, is the update pretty much done already and I just need to reboot the app and its straight away done? Sorry for my stupidity, I am not very advanced with tech.

**Comment by ltGuillaume** [comment]
Are you still on v1.2.1?
