### ISSUE TITLE
XULRunner Error when updating Librewolf Portable

### ISSUE THREAD

**Issue by FrostBlade5** [ltGuillaume/LibreWolf-WinUpdater#13]
![Capture](https://user-images.githubusercontent.com/91756004/194696954-b379ecac-c661-4383-b07d-d0eb2359d6c8.PNG)

**Comment by ltGuillaume** [comment]
Hi,

This isn't directly related to the updater, but I'd still like to prevent issues like this. 

Are you running the latest WinUpdater? If so, can you perhaps create a zip file of the LibreWolf folder (containing librewolf.exe) and upload it somewhere for me, like https://upload.disroot.org ?

**Comment by ltGuillaume** [comment]
https://teddit.zaggy.nl/r/LibreWolf/comments/xwtoig/error_while_updating/ was you? I'm closing this.

**Comment by FrostBlade5** [comment]
> https://teddit.net/r/LibreWolf/comments/xwtoig/error_while_updating/ was you? I'm closing this.

Sorry for the late reply, that wasn't me on teddit.
I ended up reinstalling librewolf latest version manually and got the latest updater version aswell, my bad i didn't provide the requestes zip file. I can say only so much it everything seems to work now with the latest versions.
