### ISSUE TITLE
Error "Could not download the releases file..." since version 1.4.0

### ISSUE THREAD

**Issue by GeniusBroccoli** [ltGuillaume/LibreWolf-WinUpdater#15]
Hi. I have error "Could not download the releases file..." since version 1.4.0, url link from script "https://gitlab.com/api/v4/projects/13852981/releases/permalink/latest" opens in my browser correctly, what could be the problem?

P.S. Problem on old PC with win 7.

**Comment by ltGuillaume** [comment]
You'll need to enable the use of TLSv1.2 for Windows/Internet Explorer:

1. In the Start Menu, type **Internet Options** and open it
2. Go to the **Advanced** tab
3. Scroll down and enable the check next to **Use TLS 1.2**:

    ![image](https://user-images.githubusercontent.com/4777345/200134959-fc244081-487c-4bcd-87fe-269217d80fb9.png)

**Comment by GeniusBroccoli** [comment]
Checked, I have SSL 1.2 enabled.
A long time ago, after upgrading from 1.3.4 to 1.4.0, I first got the error, but I ignored it and continued using 1.3.4. Now I decided to check all versions from 1.3.4 to 1.4.3 and all 1.4.0+ give the error, but 1.3.4 works fine.

**Comment by ltGuillaume** [comment]
Then you'll really need to update your Windows installation, in order to allow for Schannel to support more ciphersuites.

You'll probably need this hotfix:
https://catalog.update.microsoft.com/search.aspx?q=kb3140245

Source: https://support.microsoft.com/en-us/topic/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-winhttp-in-windows-c4bd73d2-31d7-761e-0178-11268bb10392

**Comment by GeniusBroccoli** [comment]
@ltGuillaume 
Thank you!
My Windows 7 updated, the error was fixed by the registry settings from the Microsoft article you linked to! Specifically:

```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Internet Settings\WinHttp
Add DefaultSecureProtocols 0x00000A00
```
```
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Client
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.2\Client
Add DisabledByDefault 0
```

I did not even reboot the PC and the new updater 1.4.3 worked without errors.

**Comment by ltGuillaume** [comment]
Great! 👍

**Comment by Templayer** [comment]
Enabling TLS 1.2 helped me. Thank you!
