### ISSUE TITLE
Consider mirroring repos to Codeberg

### ISSUE THREAD

**Issue by throwawayaccountfor** [ltGuillaume/LibreWolf-WinUpdater#16]
Hello @ltGuillaume We should mirror our repos to Codeberg because:
1. Codeberg is libre, free, open-source, privacy-friendly, non-profit
2. GitHub is privacy-invasive, proprietary
3. People on Codeberg like me can contribute to the project
4. GitHub can take down your repos

Here are some sources for you:
1. https://sfconservancy.org/GiveUpGitHub
2. https://github.com/humanetech-community/awesome-humane-tech/issues/33
3. https://github.com/ungoogled-software/ungoogled-chromium/discussions/1894
4. https://cadence.moe/blog/2022-07-03-git-forge-opinions-github-gitlab-gitea-sourcehut
5. https://github.com/andersju/webbkoll/issues/35
6. https://docs.codeberg.org/advanced/migrating-repos

### FAQ
1. **Q:** - GitHub Actions -- this is a huge time saver for me
          - Forcing all contributors to modify their current setup and move to another hosting -- we may just lose contributors in the end
    
   **A:** As I said, we only just _mirror_. The repo will be available and contributable on **both** sites.

2. **Q:** - Transferring issues -- is this possible? Issues here represent a technical knowledge base we can't live without
          - Transferring wiki and all edit history -- possible?

    **A:** Yes, it is possible.
a. Example for issues:

- https://github.com/andersju/webbkoll/issues/35
- https://codeberg.org/dataskydd.net/webbkoll/issues/35
- https://github.com/andersju/webbkoll/issues/33
- https://codeberg.org/dataskydd.net/webbkoll/issues/33
- https://github.com/zyachel/quetre/issues/7
- https://codeberg.org/zyachel/quetre/issues/7

b. Example for commits:
- https://codeberg.org/dataskydd.net/webbkoll/commit/6ddfbc6c71ab92f754252dd4904cf49fb19672a6
- https://github.com/andersju/webbkoll/commit/6ddfbc6c71ab92f754252dd4904cf49fb19672a6

c. Example for wiki:
- https://github.com/Freeyourgadget/Gadgetbridge/wiki/Home/_history?page=2
- https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Home?action=_revision

3. **Q:** Despite having mirror/s, the project will still continue to be operated from GitHub for development, so having yet another mirror doesn't solve anything.

   **A:** You can create issues, contribute, view the repos on there without going to GitHub! Example:
- https://github.com/libredirect/libredirect
- https://codeberg.org/LibRedirect/libredirect
- https://github.com/zyachel/quetre
- https://codeberg.org/zyachel/quetre

4. **Q:** How does Codeberg mirror comments from GitHub?
   
   **A:** It uses Access Token. 
   ![image](https://user-images.githubusercontent.com/121148372/209098935-5b16df71-9832-4e2f-8a12-e8911d5e7e66.png)

5. **Q:** My repos are very bandwidth-intensive projects, and I have my doubts as to whether the owner(s) of Codeberg would be prepared for such a massive bandwidth rate increase. I've also had individual projects be disabled on small sites before due to taking too much bandwidth.

   **A:** Oh.. I think you should directly ask https://docs.codeberg.org/contact/ about if they are ready for massive bandwidth rate increase.

**Comment by throwawayaccountfor** [comment]
But nothing happened and no discussion at all?

**Comment by ltGuillaume** [comment]
I was looking at the account and considered it to be a bit spammy to my taste. But rest assured, I was already looking into this.

I found [this](https://fossnix.netlify.app/mirror-github-to-codeberg) as a template, but I have to figure out how the .gitconfig example actually does its job before applying it.

**Comment by throwawayaccountfor** [comment]
> spammy

Yeah, I also felt so. I just copied content from my other issues to here because there’s nothing to change really. How can I make it less spammy-feeling? Appreciate any suggestions for writing issues!

> But rest assured, I was already looking into this.
>
> I found [this](https://fossnix.netlify.app/mirror-github-to-codeberg) as a template, but I have to figure out how the .gitconfig example actually does its job before applying it.

Thank you for taking a look at this!

**Comment by ltGuillaume** [comment]
Well, for one, keep it short. You can put the nfo you've gathered in a wiki or something (here or on Codeberg), then:

1. Explain in 1 or 2 sentences the rationale to migrate or mirror
2. Link to 1 or 2 sources for (1)
3. Then link to a single tutorial that explains how to migrate or mirror.
4. Add a link the info you've already gathered and posted here.

As far as I know there is no use whatsoever to show me or other devs repos that already mirrored to Codeberg as examples, because it doesn't show how to do so.

**Comment by throwawayaccountfor** [comment]
> Well, first, use a different account name. Second, keep it short. 

Changed! Thanks!

**Comment by throwaway-d** [comment]
> You can put the nfo you've gathered in a wiki or something (here or on Codeberg)

Done! Thanks!
https://codeberg.org/HexagonCDN/Mirroring_repos_to_Codeberg

**Comment by throwaway-d** [comment]
> Then link to a single tutorial that explains how to migrate or mirror.

[It's still in WIP](https://codeberg.org/HexagonCDN/Mirroring_repos_to_Codeberg/pulls/1)

**Comment by throwaway-d** [comment]
> As far as I know there is no use whatsoever to show me or other devs repos that already mirrored to Codeberg as examples, because it doesn't show how to do so.

I mean they are using a workflow to mirror to Codeberg and I think you could look at it: https://github.com/nesaku/BiblioReads/blob/main/.github/workflows/codeberg-mirror.yml

**Comment by ltGuillaume** [comment]
https://codeberg.org/ltGuillaume

**Comment by throwaway-d** [comment]
When you figure out, please tell me so I can add it to the tutorial on my repo!

**Comment by throwaway-d** [comment]
https://github.com/libredirect and https://github.com/zyachel have been mirroring their repos to Codeberg for a very long time. Maybe we should ping them and ask for help?

**Comment by throwaway-d** [comment]
@ltGuillaume We have the tutorial now! https://codeberg.org/Recommendations/Mirror_to_Codeberg#setting-up-github-codeberg-mirroring

**Comment by ltGuillaume** [comment]
Thanks, yeah, looks good!

**Comment by throwaway-d** [comment]
When it works, please tell me! :D

**Comment by ltguillaume** [comment]
Just thought you'd want to know that a week ago I started using Codeberg as primary remote and now let Codeberg sync to GitHub with access tokens.

**Comment by throwaway-d** [comment]
Great!

**Comment by throwaway-d** [comment]
Thank you for informing me!
