### ISSUE TITLE
Autoupdate for non Portable Version

### ISSUE THREAD

**Issue by LiberteIV** [ltGuillaume/LibreWolf-WinUpdater#17]
I've got both librewolf version portable and non portable.
The portable always starts the updater when i open it which i like alot because in this scenario the updater does what it's supposed to do, scan for updates and install them if found.
With the non portable version i'm having a hard time here, it never starts the updater when opened.
I did use the powershell file for automatic updates however duo to my system configuration powershell has no network access for privacy reasons, basically my whole os is blocked from accesing the internet expect if i allow it individualy.
So i manually need to run the updater for the non portable version from time to time or i wont get any updates at all.
I could ofcourse use the portable version as the main browser and the issue would be solved.
But the portable version is noticable slower than the non portable, so i preffer to use it as the main browser.

Would it be possible to configure the updater for the non portable librewolf version so it will scan for updates whenever the browser is started just like it works with the portable version?

**Comment by LiberteIV** [comment]
I tought it must be powershell or taskscheduler causing the updates to not ever happen.
As i said the update task is active in taskscheduler, but for whatever reason it never runs.

Edit, i deleted the powershell task and tried to re-create it.
Result:
```
Register-ScheduledTask : The parameter is incorrect.
(23,8):UserId:
At C:\Program Files\LibreWolf\ScheduledTask-Create.ps1:17 char:1
+ Register-ScheduledTask -TaskName "LibreWolf WinUpdater ($User)" -Acti ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (PS_ScheduledTask:Root/Microsoft/...S_ScheduledTask) [Register-Schedule
   dTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070057,Register-ScheduledTask

Done.
```

It might very well be that my imagination caused me to think the portable version is slower than the other..

**Comment by LiberteIV** [comment]
Trying to create a task by myself, can i devine C:\Windows\system32\cmd.exe as script and "C:\Program Files\LibreWolf\LibreWolf-WinUpdater.exe" as argument, will that work? 
And if i use "run the task on a schedule" should i check the option "synchronize across timezones", does it matter?

**Comment by LiberteIV** [comment]
I don't know why the file to add the task doesn't work, it did before.

**Comment by ltGuillaume** [comment]
> Trying to create a task by myself, can i devine C:\Windows\system32\cmd.exe as script and "C:\Program Files\LibreWolf\LibreWolf-WinUpdater.exe" as argument, will that work? And if i use "run the task on a schedule" should i check the option "synchronize across timezones", does it matter?

![image](https://user-images.githubusercontent.com/4777345/217147417-39f87bb1-f91f-49c8-882f-ae2f49e6ac95.png)

**Comment by LiberteIV** [comment]
![Capture](https://user-images.githubusercontent.com/116210112/217206677-9fce827f-97b6-4f6a-ad1c-8296b9bc1832.PNG)

**Comment by LiberteIV** [comment]
In the virtualmachine it worked, i probably messed something up on my system, otherwise your "add schedule task" should work.
Problem must be on my side.

Anyways i took another look at your schedule tasks and i get it now why it doesnt work.
I always boot my system offline and before going offline i also make sure there is no network connection, this is to prevent my windows computer from sending any data to microsoft, while the pc is online i have portmaster running (replacement for windows firewall) so i'm as private as it can get. But during the boot and shutdown, portmaster is not active so i dont like that.

Your task as you know is triggered after logon, well after logon i am always offline and just like one minute after im online so thas where it fails, suggestions?

Also i just noticed that downloading latest portable librewolf includes your updates by default, thats a great change.
Wish the non portable version was easier to update. Scan for updates on each browser start would be dream.

**Comment by ltGuillaume** [comment]
Yeah I couldn't make anything of your error message because it's been cut off, so now idea how I can help you there.

> Anyways i took another look at your schedule tasks and i get it now why it doesnt work.
I always boot my system offline and before going offline i also make sure there is no network connection, this is to prevent my windows computer from sending any data to microsoft, while the pc is online i have portmaster running (replacement for windows firewall) so i'm as private as it can get. But during the boot and shutdown, portmaster is not active so i dont like that.

Doesn't matter, because it should repeat every 4 hours anyway.

**Comment by LiberteIV** [comment]
Hm really don't know why on my main OS the ScheduledTask-Create.ps1 isn't working.
![2](https://user-images.githubusercontent.com/116210112/217239878-84d201ad-d6be-4657-9698-2b5d3e48e941.PNG)

**Comment by LiberteIV** [comment]
Is there any specific reason why you preffer running the updater scheduled every 4 hours instead of on each start of librewolf?
Could i "fork" the updater from the non portable version so it's triggered on each start? I mean, i don't know how that would be done.
