### ISSUE TITLE
Download URL could not be found

### ISSUE THREAD

**Issue by CountCypher** [ltguillaume/librewolf-winupdater#19]
Hi!

First of all, thanks for your work on this software. Highly appreciated! :)

Using version 1.5.1 of the updater and the portable version 110.0-1 of LibreWolf on Windows, I get this error from the updater when starting LibreWolf:

![image](https://user-images.githubusercontent.com/54265000/226298563-455ee5b9-1aeb-41f6-8155-dcd07902beda.png)

And after acknowledging the message, no update is found and LibreWolf starts.
As version 111 of LibreWolf is out, I would expect that this is picked up and installed by the updater instead.

**Comment by ltguillaume** [comment]
I think you're not using LibreWolf WinUpdater 1.5.1, but 1.5.0. Please update the file `LibreWolf-WinUpdater.exe` manually by extracting it from https://github.com/ltguillaume/librewolf-winupdater/releases/download/1.5.1/LibreWolf-WinUpdater_1.5.1.zip and overwriting your current `LibreWolf-WinUpdater.exe`.

Again, I am truly sorry about the way this transpired. I wish I was properly informed about the changes being made to the release system beforehand, so I could have tested it before they were made public.

**Comment by CountCypher** [comment]
You're right. I really thought that had updated WinUpdater to version 1.5.1, but in fact I've missed it. Sorry for that. :( Works good now after the update.
Thanks for the quick reply!

**Comment by ltguillaume** [comment]
Great! And no worries of course!
