### ISSUE TITLE
infinite loop update check

### ISSUE THREAD

**Issue by sq787** [ltGuillaume/LibreWolf-WinUpdater#2]
In some cases, LibreWolf version notation in Releases and the program do not match. So, even after completing the update to the current version, it continues to incorrectly recognize the current version as a new version.

e.g.)
* Versions on Releases: 99.0.1.2
* Internally indicated version: 99.0.1-4

**Comment by ltGuillaume** [comment]
Thanks for reporting. Yes, the versioning used by LibreWolf is inconsistent, so it's difficult to compare the installed version with the version in the release file.

So, I've added an extra check to compare the current version in the release file as downloaded from Gitlab with the version number WinUpdater now saves to its ini-file, if it updated successfully, which has the version formatting of the release file, not of the exe-file. This should prevent the infinite update loop.

Could you have a look and test it?

**Comment by sq787** [comment]
Great!👍

**Comment by ltGuillaume** [comment]
I do hate the idea of "an updater needing updates", though 😅 And unfortunately, the updater isn't bundled with e.g. the LibreWolf portable zip-file, so it won't be fixed for users automatically due to a LibreWolf update. Ah well, it's an imperfect world.

**Comment by ltGuillaume** [comment]
Well, it survived the "versioning mess" as stanzabird called it himself, so I guess we know this is fully fixed 😛
