### ISSUE TITLE
Issue running ScheduledTask-Create.ps1

### ISSUE THREAD

**Issue by Jaladhjin** [ltguillaume/librewolf-winupdater#20]
Hello!

I've got 3 PCs I've been trying to set this up on.

On 1 of them it asked me to change the elevation or access permissions or something with a Yes, Yes To All, No, No To All, Cancel.

But then on the other 2 PCs not copying the folder I'm creating a new folder on the local machine from the .zip download of the updater I receive this error even if running ScheduledTask-create.ps1 via navigating to the directory & typing it out in a PS shell window vs just right clicking & Run With Powershell since doing that the window disappears before I can see the failure message.

Anyway the failure message is:

ScheduledTask-Create.ps1 : The term 'ScheduledTask-Create.ps1' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At line:1 char:1
+ ScheduledTask-Create.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ScheduledTask-Create.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Suggestion [3,General]: The command ScheduledTask-Create.ps1 was not found, but does exist in the current location. Windows PowerShell does not load commands from the current location by default. If you trust this command, instead type: ".\ScheduledTask-Create.ps1". See "get-help about_Command_Precedence" for more details.

Please advise!

Happy to provide whatever I can too.

My local user does have Local Administrator powers too yes.

**Comment by ltguillaume** [comment]
So what happens if you go into the folder from a PowerShell window and type in: 
`.\ScheduledTask-Create.ps1`

**Comment by ltguillaume** [comment]
> So what happens if you go into the folder from a PowerShell window and type in: `.\ScheduledTask-Create.ps1`

@Jaladhjin Any news?

**Comment by ltguillaume** [comment]
I'm closing this. Feel free to still reply when you get to it.

For what it's worth, you can also create a scheduled task for the updater manually, screenshots to guide you through that can be found at https://github.com/ltguillaume/librewolf-winupdater/issues/17#issuecomment-1420179207
