### ISSUE TITLE
sha checksum - file integrity

### ISSUE THREAD

**Issue by Abyssgrowth** [ltguillaume/librewolf-winupdater#22]
Do you provide a sha256 sum or 512 so we can verify the downloaded file hasn't been modified?
Either i must be blind or there's checksums there https://codeberg.org/ltGuillaume/LibreWolf-WinUpdater/releases

Edit, maybe a checksum could be added for download here? https://codeberg.org/ltguillaume/librewolf-winupdater/src/tag/1.6.2

**Comment by ltguillaume** [comment]
That'll probably need some changes in the script to build the `-portable.zip` releases, otherwise I might break it. I'll get back to you as soon as I know more.

SHA256 for now:
```
295d74b6190c32e38cf6056d8b35b240043ec7de59ba675516e96f697c23c2be *LibreWolf-WinUpdater_1.6.2.zip
```

**Comment by Abyssgrowth** [comment]
Thank you

**Comment by ltguillaume** [comment]
The scripts to include WinUpdater with the portable and the setup release were updated some time ago to handle which file to download, so I'll start including the sha256's from now on.
