### ISSUE TITLE
Restarting repeatedly

### ISSUE THREAD

**Issue by Craulback** [ltguillaume/librewolf-winupdater#23]
Win 11 Pro (ReviOS 23.01)
Winupdater Version 1.7.8.
I installed it through the Librewolf 1.5.0.2 installer.
Then updated manually to 1.6.0.1 to see if that would fix it.
It just keeps restarting itself, the log shows nothing useful:
```
[Log]
LastRun=10:29 AM Friday, August 4, 2023
```

https://github.com/ltguillaume/librewolf-winupdater/assets/92492424/06066bce-651b-4c13-af1b-aaed31dd5370

**Comment by ltguillaume** [comment]
Apparently you're running it with administrator privileges. It's trying to restart itself _without_ administrator privileges/unelevated, but apparently it's failing to do so. Is there anything on your system that could prevent it from doing so?

**Comment by Craulback** [comment]
Oh I'm an idiot, UAC was disabled, I should have guessed. Idk why I had it disabled, bad idea. 
My bad, thanks!

**Comment by ltguillaume** [comment]
Well, it's good that you reported this! I didn't know that UAC being disabled completely could cause this issue.

I'll have a look if I can work around this :)

**Comment by Craulback** [comment]
It still restarts indefinitely, I checked the registry key and it is indeed set to 0.

**Comment by ltguillaume** [comment]
That's odd. Can you tell me how you've disabled UAC exactly? Is `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System\EnableLUA` set to `0`? Or did you just drag down this slider?
![image](https://github.com/ltguillaume/librewolf-winupdater/assets/4777345/027db300-f430-4703-a381-1248c927a3e1)
The slider isn't actually disabling UAC and it should've worked like that to begin with, so I'm a bit confused now...

**Comment by Craulback** [comment]
I used a program called winaero tweaker, maybe there are some extra shenanigans behind the scenes since I'm also using the Revision OS version of Win 11. 

![image](https://github.com/ltguillaume/librewolf-winupdater/assets/92492424/e0c5464d-d5b1-4695-bcd0-468d4e9646ec)

**Comment by ltguillaume** [comment]
That's strange. Winaero's implementation is indeed using that registry value. And I've tested exactly this situation.

Just to be sure, can you remove all `C:\Users\[EveryUserYouHave]\AppData\Roaming\LibreWolf\WinUpdater`?
Then be sure that `C:\Program Files\LibreWolf\LibreWolf-WinUpdater.exe` is [this one](https://github.com/ltguillaume/librewolf-winupdater/files/12263317/LibreWolf-WinUpdater_CheckUACDisabled.zip) and try again?

**Comment by Craulback** [comment]
Yeah, I deleted it all and tried again just now. It says 1.7.10, restarting still.

I'm thinking it might be related to something ReviOS has removed from Windows itself, not sure I want to keep it much longer.
I've been thinking about going back to stock Win 10 and creating my own sysprep image lately, just been too lazy lol.

**Comment by ltguillaume** [comment]
I'm not familiar with ReviOS, could be. I'd say go for IoT LTSC 2021, so you can still get security updates until 2032, I'd say, unless you know of any features between 21H2 and 22H2 that you're gonna need.

Here's an updated version, not sure if it'll help, though: 
[LibreWolf-WinUpdater_CheckUACDisabled2.zip](https://github.com/ltguillaume/librewolf-winupdater/files/12264224/LibreWolf-WinUpdater_CheckUACDisabled2.zip)

**Comment by Craulback** [comment]
Ok, thanks for the recommendation I'll look into it.

It's still restarting. I'll try installing stock Win 11 on a VM to test it & get back to you.

**Comment by ltguillaume** [comment]
Ugh, strange stuff. Thank you for helping out with the debugging, much appreciated! 😃

**Comment by Craulback** [comment]
You're welcome! It works fine in legit Win 11 Pro, just restarted itself once or twice. 
The issue must be hidden somewhere in my abomination of an OS lol

**Comment by ltguillaume** [comment]
> once or twice.

Yeah, once to be run from %AppData% instead of Program Files, and once to unelevate. That's fine.

O sh*t, I've just had a look at ReviOS and Ameliorated, and I'm down the rabbit hole now. Thanks for that 😉

**Comment by Craulback** [comment]
Ahh yeah, no problem! Ameliorated is a little too stripped down for my taste, it was annoying just getting anything .NET related to install. & Revi has it's issues, like LAN sharing with vanilla PCs on the network, and you can't rename your PC, etc etc, mostly small annoyances. Some security flaws but you can turn some things back on through their Revision Tool. Good luck! Haha 😂

**Comment by ltguillaume** [comment]
Ok, so I've taken a simpler approach to preventing a restart loop that covers unknown scenario's (if there are any), too. This should help either way, otherwise the restart loop you're getting isn't even initiated by the script itself.
[LibreWolf-WinUpdater_NoInfiniteRestartLoop.zip](https://github.com/ltguillaume/librewolf-winupdater/files/12266016/LibreWolf-WinUpdater_NoInfiniteRestartLoop.zip)

**Comment by Craulback** [comment]
Indeed it worked, success on heavily modified ReviOS with no UAC!

**Comment by ltguillaume** [comment]
Great! I'll release an update then 🙂

Thanks for helping out! 😃

**Comment by Craulback** [comment]
You're welcome, I admire your dedication. 

I'm still ditching ReviOS though lol!
