### ISSUE TITLE
Error when trying to use the updater - could not find URL

### ISSUE THREAD

**Issue by githubchk111** [ltguillaume/librewolf-winupdater#24]
![Screenshot (5684)](https://github.com/ltguillaume/librewolf-winupdater/assets/141740691/a660a61d-a205-4b4c-878e-05ef77e9f16c)

**Comment by ltguillaume** [comment]
That is a _very_ old version. Please update to the latest version: https://codeberg.org/ltguillaume/librewolf-winupdater/releases/latest

After doing this, WinUpdater will also update itself when necessary.
