### ISSUE TITLE
Does the updater overwrite user modified settings to stock?

### ISSUE THREAD

**Issue by knownbyfew** [ltGuillaume/LibreWolf-WinUpdater#3]
Hey,

So, I just found out about Librewolf this week and I wanted to try it as I've been using the Mozilla Firefox for about 5 years now and I'm used to the ecosystem.

And as per the official Librewolf page, they link your extension as a secondary unofficial way of updating the browser, so I wanted to ask - was this extension created to make Firefox users more familiar with the updating process of the browser and also will it overwrite all the settings that I've modified and revert it back to stock?

I apologize in advance if this isn't the correct platform to ask such questions.

Thanks for reading.

**Comment by ltGuillaume** [comment]
1. This is _not_ the extension.
2. People should be able to contact its author easily, but I don't know how.
3. The extension only _checks_ for updates. It will _not_ do any changes.
4. _This_ program is completely separate from that extension.
5. It can check _and_ update either installed LibreWolf instances, or the portable version.
6. It will only update the LibreWolf program files, leaving your profile completely intact. No settings will be reverted.
7. A new `librewolf.cfg` coming with the updated LibreWolf can introduce changed or overriding settings. This is all to the LibreWolf team's discretion.
