### ISSUE TITLE
Could not find the URL to the checksum file

### ISSUE THREAD

**Issue by kevinfiol** [ltGuillaume/LibreWolf-WinUpdater#6]
![OGDysQpifG](https://user-images.githubusercontent.com/4752973/171726361-1ab90a87-76d5-4bca-908f-a906c2467f4d.png)

Starting having this issue today. Seems like the script may be failing to get the checksums file. Did the URL change? Not sure if this may be due to my firewall settings. 😓

**Comment by ltGuillaume** [comment]
Hey there! Are you running the latest version of LibreWolf WinUpdater, v1.3.3?

**Comment by ltGuillaume** [comment]
Got it, thanks! See https://github.com/ltGuillaume/LibreWolf-WinUpdater/releases/tag/1.3.4

**Comment by kevinfiol** [comment]
Thanks @ltGuillaume ! That did the trick. 👍
