### ISSUE TITLE
Scheduled Task creation results in "Cannot validate argument on parameter... "

### ISSUE THREAD

**Issue by wefalltomorrow** [ltGuillaume/LibreWolf-WinUpdater#9]
Running 'ScheduledTask-Create.ps1' from context menu with "Run as Powershell" in a folder with full write permissions "*\AppData\Roaming\LibreWolf\LibreWolf-WinUpdater" and I get the follow error relating to "user".

Any ideas what this could be?

![image](https://user-images.githubusercontent.com/45746576/179338580-306f58c1-ddee-437d-b881-15cbf7c47d18.png)

**Comment by ltGuillaume** [comment]
Apparently you're running the script directly with Administrator privileges. Are you right-clicking `ScheduledTask-Create.ps1` from another program/file manager than Explorer?

**Comment by ltGuillaume** [comment]
I've changed the scripts to allow being run from an elevated program, see
https://github.com/ltGuillaume/LibreWolf-WinUpdater/blob/nopowershell/ScheduledTask-Create.ps1 and
https://github.com/ltGuillaume/LibreWolf-WinUpdater/blob/nopowershell/ScheduledTask-Remove.ps1

**Comment by ltGuillaume** [comment]
Included in v1.4.0.

@wefalltomorrow I hope this has fixed everything for you?
